// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwUziygEL0U00G0bmJr2oNUOhH_GAcQt8',
    appId: '1:548967203383:web:a235b484cedc5e8677b5b2',
    messagingSenderId: '548967203383',
    projectId: 'totemic-fact-477116-k2',
    authDomain: 'totemic-fact-477116-k2.firebaseapp.com',
    storageBucket: 'totemic-fact-477116-k2.firebasestorage.app',
    measurementId: 'G-Z70THJ1THV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA77tTopk1LA-0SSGFmK_1JdHE4TF1Uzg',
    appId: '1:548967203383:android:0da41b973b1495ae77b5b2',
    messagingSenderId: '548967203383',
    projectId: 'totemic-fact-477116-k2',
    storageBucket: 'totemic-fact-477116-k2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFnH-R0icLQLMk3Oy7MhUvJP0QWayNjdg',
    appId: '1:548967203383:ios:d0fc570b3b51a3e477b5b2',
    messagingSenderId: '548967203383',
    projectId: 'totemic-fact-477116-k2',
    storageBucket: 'totemic-fact-477116-k2.firebasestorage.app',
    iosBundleId: 'com.example.fastRoute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFnH-R0icLQLMk3Oy7MhUvJP0QWayNjdg',
    appId: '1:548967203383:ios:d0fc570b3b51a3e477b5b2',
    messagingSenderId: '548967203383',
    projectId: 'totemic-fact-477116-k2',
    storageBucket: 'totemic-fact-477116-k2.firebasestorage.app',
    iosBundleId: 'com.example.fastRoute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwUziygEL0U00G0bmJr2oNUOhH_GAcQt8',
    appId: '1:548967203383:web:2cf3795ab70b65fe77b5b2',
    messagingSenderId: '548967203383',
    projectId: 'totemic-fact-477116-k2',
    authDomain: 'totemic-fact-477116-k2.firebaseapp.com',
    storageBucket: 'totemic-fact-477116-k2.firebasestorage.app',
    measurementId: 'G-T5T7STX98T',
  );
}
